---
- name: Deploy K3s homelab infrastructure
  hosts: homelab
  become: yes
  tasks:
    - name: Install Git
      ansible.builtin.include_role:
        name: git
      tags: base, git

    - name: Configure K3s
      ansible.builtin.include_role:
        name: k3s
      tags: server, k3s

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers
      tags: server, k3s