---
- name: Deploy K3s homelab infrastructure
  hosts: homelab
  become: yes
  tasks:
    - name: Install Git
      ansible.builtin.include_role:
        name: git
      tags: base, git

    - name: Configure K3s
      ansible.builtin.include_role:
        name: k3s
      tags: server, k3s

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers
      tags: server, k3s

    - name: Configure nginx-ingress
      ansible.builtin.include_role:
        name: nginx-ingress
      tags: server, ingress

    - name: Configure cert-manager
      ansible.builtin.include_role:
        name: cert-manager
      tags: server, ssl

    - name: Install and configure PostgreSQL
      ansible.builtin.import_role:
        name: postgresql
      tags: server, database