all:
  children:
    homelab:
      hosts:
        home_server:
          ansible_connection: ssh
          ansible_host: 192.168.45.191
          ansible_user: iskang-ubuntu
          ansible_ssh_private_key_file: /Users/kanginsung/.ssh/homeserver